#!/usr/bin/env bash

DIR_CONTEXT="."
TAG_PREFIX="local/build"
SHELL_PATH=""

if [ -z "${2}" ]; then true; else
	TAG_PREFIX=${2}
fi

if [ -z "${3}" ]; then true; else
	SHELL_PATH=${3}
fi

IMAGE_TAG=$(openssl rand -hex 4)
IMAGE_TAG="${TAG_PREFIX}_${IMAGE_TAG}"

echo "Building ${DIR_CONTEXT} as ${IMAGE_TAG} ...";
echo "";

# Build image
docker build ${DIR_CONTEXT} -t ${IMAGE_TAG}

if [ $? -eq 0 ]; then
    
    echo "Launching container from ${IMAGE_TAG} ...";
	echo "";

	CONTAINER_ID=$(docker run -d -P --rm ${IMAGE_TAG})

	if [ $? -eq 0 ]; then
		# Attach shell
		docker-shell ${CONTAINER_ID} ${SHELL_PATH}
	fi


fi
