#!/usr/bin/env bash

APP_ID="${1}";
APP_SC="${2}";

if [ -z "${APP_ID}" ] || [ -z "${APP_SC}" ]; then 
	echo "Please enter your Facebook App Id and App Secret!";
	exit 1;
fi

URL="https://graph.facebook.com/oauth/access_token?client_id=${APP_ID}&client_secret=${APP_SC}&redirect_uri=http://localhost/test&grant_type=client_credentials";

curl -X GET "${URL}";
