#!/usr/bin/env bash

APP_TOKEN="${1}";
DEBUG_TOKEN="${2}";

if [ -z "${APP_TOKEN}" ] || [ -z "${DEBUG_TOKEN}" ]; then 
	echo "Please enter your Facebook App Token and the token you'd like to debug!";
	echo "Usage: ${0} <app-token> <debug-token>";
	exit 1;
fi

URL="https://graph.facebook.com/debug_token?input_token=${DEBUG_TOKEN}&access_token=${APP_TOKEN}";

echo ""; # Newline
echo "Debug information for token ${DEBUG_TOKEN} ...\n";
curl -X GET "${URL}";
