#!/usr/bin/env bash

echo ""; # Newline
echo "HTTP headers for ${1}";
echo "--------------------------------------------------"

curl -s -D - "$1" -o /dev/null

echo "--------------------------------------------------"
